# Generated by Django 5.0 on 2024-10-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_ekskul_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatif',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
