# Generated by Django 5.0 on 2024-10-14 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_ekskul_app', '0002_alter_alternatif_nama_alter_kriteria_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='kriteria',
            name='bobot',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='jenis',
            field=models.CharField(choices=[('BENEFIT', 'BENEFIT'), ('COST', 'COST')], default='benefit', max_length=10),
        ),
        migrations.CreateModel(
            name='NilaiEkskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spk_ekskul_app.alternatif')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spk_ekskul_app.kriteria')),
            ],
        ),
    ]
