# Generated by Django 5.0 on 2024-10-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_ekskul_app', '0003_ekskul_kriteria_bobot_alter_kriteria_jenis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ekskul',
            old_name='name',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='ekskul',
            name='description',
        ),
        migrations.CreateModel(
            name='SubKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=3)),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subkriteria', to='spk_ekskul_app.kriteria')),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spk_ekskul_app.ekskul')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spk_ekskul_app.kriteria')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='spk_ekskul_app.alternatif')),
                ('sub_kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spk_ekskul_app.subkriteria')),
            ],
        ),
        migrations.DeleteModel(
            name='NilaiEkskul',
        ),
    ]
