# Generated by Django 5.0 on 2024-10-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_ekskul_app', '0004_rename_name_ekskul_nama_remove_ekskul_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penilaian',
            old_name='siswa',
            new_name='alternatif',
        ),
        migrations.RemoveField(
            model_name='penilaian',
            name='ekskul',
        ),
        migrations.RemoveField(
            model_name='penilaian',
            name='sub_kriteria',
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='kriteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='spk_ekskul_app.kriteria'),
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='nilai',
            field=models.FloatField(),
        ),
    ]
