# Generated by Django 5.0 on 2024-10-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_ekskul_app', '0006_penilaian_ekskul_alter_penilaian_alternatif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaian',
            name='nilai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_nilai', to='spk_ekskul_app.subkriteria'),
        ),
    ]
