# Generated by Django 5.0 on 2024-10-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_ekskul_app', '0007_alter_penilaian_nilai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaian',
            name='kriteria',
        ),
        migrations.RemoveField(
            model_name='penilaian',
            name='nilai',
        ),
        migrations.AddField(
            model_name='penilaian',
            name='c1',
            field=models.ForeignKey(default=True, limit_choices_to={'kriteria__simbol': 'C1'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c1', to='spk_ekskul_app.subkriteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaian',
            name='c2',
            field=models.ForeignKey(default=True, limit_choices_to={'kriteria__simbol': 'C2'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c2', to='spk_ekskul_app.subkriteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaian',
            name='c3',
            field=models.ForeignKey(default=True, limit_choices_to={'kriteria__simbol': 'C3'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c3', to='spk_ekskul_app.subkriteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaian',
            name='c4',
            field=models.ForeignKey(default=True, limit_choices_to={'kriteria__simbol': 'C4'}, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_c4', to='spk_ekskul_app.subkriteria'),
            preserve_default=False,
        ),
    ]
